[programs.localnet]
countertest = "AuKBLAeS5MSzXL8KDNiSzu4ddaAGNVVGmuFtLvJ5Cwoz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/moly/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
